[package]
name = "ascender"
version = "0.1.0"
authors = ["Ash <relativistic.policeman@gmail.com>"]

[dependencies]
ansi_term = "0.11"
failure = "0.1"
image = "0.19"
itertools = "0.7"
palette = "0.4"
rusttype = "0.6"
structopt = "0.2" # Only for the binary.